//! Registry of Engine microbenchmarks and their optional in-process runners.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum BenchRunnerKind {
    Engine,
    Matmul,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct BenchSpec {
    pub id: &'static str,
    pub bin: &'static str,
    pub kind: &'static str,
    pub summary: &'static str,
    pub default_args: &'static str,
    pub runner: Option<BenchRunnerKind>,
    pub requires_alloc_profile: bool,
}

pub const BENCHES: &[BenchSpec] = &[
    BenchSpec {
        id: "engine",
        bin: "auralis_engine_bench",
        kind: "throughput",
        summary: "side-by-side train reference vs reuse",
        default_args: "3 20 5",
        runner: Some(BenchRunnerKind::Engine),
        requires_alloc_profile: false,
    },
    BenchSpec {
        id: "matmul",
        bin: "auralis_matmul_bench",
        kind: "kernel",
        summary: "forward matmul reference",
        default_args: "5 40 5",
        runner: Some(BenchRunnerKind::Matmul),
        requires_alloc_profile: false,
    },
    BenchSpec {
        id: "matmul-bt",
        bin: "auralis_matmul_bt_bench",
        kind: "kernel",
        summary: "B-transpose matmul",
        default_args: "5 40 5",
        runner: None,
        requires_alloc_profile: false,
    },
    BenchSpec {
        id: "matmul-blocked",
        bin: "auralis_matmul_blocked_bench",
        kind: "kernel",
        summary: "blocked matmul candidate",
        default_args: "",
        runner: None,
        requires_alloc_profile: false,
    },
    BenchSpec {
        id: "kernel-grad-b",
        bin: "auralis_kernel_bench",
        kind: "kernel",
        summary: "matmul grad-B kernel",
        default_args: "5 40 5",
        runner: None,
        requires_alloc_profile: false,
    },
    BenchSpec {
        id: "attention",
        bin: "auralis_attention_bench",
        kind: "kernel",
        summary: "attention forward",
        default_args: "5 80 5",
        runner: None,
        requires_alloc_profile: false,
    },
    BenchSpec {
        id: "attention-backward",
        bin: "auralis_attention_backward_bench",
        kind: "kernel",
        summary: "attention backward",
        default_args: "5 80 5",
        runner: None,
        requires_alloc_profile: false,
    },
    BenchSpec {
        id: "external-memory",
        bin: "auralis_memory_bench",
        kind: "brain-memory",
        summary: "external-memory retrieval, capacity and persistence",
        default_args: "128 40",
        runner: None,
        requires_alloc_profile: false,
    },
    BenchSpec {
        id: "memory-model",
        bin: "auralis_memory_model_bench",
        kind: "brain-memory",
        summary: "opt-in model-memory retrieval/fusion task and cost",
        default_args: "100 7",
        runner: None,
        requires_alloc_profile: false,
    },
    BenchSpec {
        id: "recurrent-reasoning",
        bin: "auralis_recurrent_reasoning_bench",
        kind: "brain-reasoning",
        summary: "shared-weight recurrent reasoning quality/cost curve",
        default_args: "",
        runner: None,
        requires_alloc_profile: false,
    },
    BenchSpec {
        id: "kv-cache",
        bin: "auralis_kv_cache_bench",
        kind: "brain-generation",
        summary: "cached vs uncached autoregressive decode latency and memory",
        default_args: "",
        runner: None,
        requires_alloc_profile: false,
    },
    BenchSpec {
        id: "gqa-mqa",
        bin: "auralis_gqa_mqa_bench",
        kind: "brain-attention",
        summary: "MHA vs GQA/MQA quality, decode latency and KV-cache memory",
        default_args: "",
        runner: None,
        requires_alloc_profile: false,
    },
    BenchSpec {
        id: "local-attention",
        bin: "auralis_local_attention_bench",
        kind: "brain-attention",
        summary: "dense vs causal local-window quality, scaling and probability-cache memory",
        default_args: "",
        runner: None,
        requires_alloc_profile: false,
    },
    BenchSpec {
        id: "moe-router",
        bin: "auralis_moe_router_bench",
        kind: "brain-moe",
        summary: "deterministic top-k routing, capacity/fallback and dispatch/gather overhead",
        default_args: "",
        runner: None,
        requires_alloc_profile: false,
    },
    BenchSpec {
        id: "reasoning-suite",
        bin: "auralis_reasoning_suite_bench",
        kind: "research-reasoning",
        summary: "deterministic synthetic reasoning smoke/full generation and objective scoring",
        default_args: "both",
        runner: None,
        requires_alloc_profile: false,
    },
    BenchSpec {
        id: "memory-suite",
        bin: "auralis_memory_suite_bench",
        kind: "research-memory",
        summary: "objective external-memory retrieval, conflict, stale, horizon and capacity suite",
        default_args: "both",
        runner: None,
        requires_alloc_profile: false,
    },
    BenchSpec {
        id: "code-suite",
        bin: "auralis_code_suite_bench",
        kind: "research-code",
        summary: "executable Rust compile/test/patch scoring with protected tests",
        default_args: "both",
        runner: None,
        requires_alloc_profile: false,
    },
    BenchSpec {
        id: "capability-suite",
        bin: "auralis_capability_suite_bench",
        kind: "research-capability",
        summary: "modular reasoning/code/memory battery with isolated regressions and reserved agent",
        default_args: "smoke",
        runner: None,
        requires_alloc_profile: false,
    },
    BenchSpec {
        id: "profile-alloc",
        bin: "auralis-profile",
        kind: "memory",
        summary: "engine allocation profile (reference vs reuse)",
        default_args: "2",
        runner: None,
        requires_alloc_profile: true,
    },
    BenchSpec {
        id: "profile-train",
        bin: "auralis_train_profile",
        kind: "memory",
        summary: "train-path allocation profile",
        default_args: "",
        runner: None,
        requires_alloc_profile: false,
    },
    BenchSpec {
        id: "profile-eval",
        bin: "auralis_eval_profile",
        kind: "memory",
        summary: "eval-path allocation profile",
        default_args: "",
        runner: None,
        requires_alloc_profile: false,
    },
];


pub const INTERNAL_ONLY_BINS: &[&str] = &[
    "auralis_bench_result_smoke",
    "auralis_workspace_profile",
    "auralis_training_diagnostics_bench",
    "auralis_forward_diagnostics_bench",
    "auralis_matmul_rowslices_vs_blocked_bench",
    "auralis_engine_soak",
    "auralis_engine_step_timing_bench",
];
